allowBuilds:
  '@google/genai': false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
minimumReleaseAgeExclude:
  - '@earendil-works/chord@1.1.0'
  - '@earendil-works/pi-agent-core@1.1.0'
  - '@earendil-works/pi-ai@1.1.0'
  - '@earendil-works/pi-codemode@1.1.0'
  - '@earendil-works/pi-coding-agent@1.1.0'
  - '@earendil-works/pi-mcp@1.1.0'
  - '@earendil-works/pi-telemetry@1.1.0'
  - '@earendil-works/pi-tui@1.1.0'
